# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: en-US
tone_instructions: >-
    Focus on file tailing correctness, cross-platform compatibility,
    tomb-to-context migration, and backward API compatibility.
    Prioritize race safety, resource cleanup, and error handling.
    Go library -- keep public API minimal and stable.
early_access: true
enable_free_tier: true
reviews:
    profile: assertive
    request_changes_workflow: true
    high_level_summary: true
    high_level_summary_placeholder: "@coderabbitai summary"
    high_level_summary_in_walkthrough: true
    auto_title_placeholder: "@coderabbitai"
    auto_title_instructions: "Use conventional commit format: <type>(<scope>): <description>"
    review_status: true
    commit_status: true
    fail_commit_status: false
    collapse_walkthrough: true
    changed_files_summary: true
    sequence_diagrams: true
    estimate_code_review_effort: true
    assess_linked_issues: true
    related_issues: true
    related_prs: true
    suggested_labels: true
    auto_apply_labels: true
    suggested_reviewers: true
    auto_assign_reviewers: true
    poem: true
    labeling_instructions:
        - label: "type:feature"
          instructions: "Use for new functionality and enhancements"
        - label: "type:bug"
          instructions: "Use for bug fixes and defect corrections"
        - label: "priority:critical"
          instructions: "Use for critical issues and urgent fixes"
        - label: "priority:high"
          instructions: "Use for high priority issues and important features"
        - label: "priority:normal"
          instructions: "Use for standard work and regular features"
        - label: "go"
          instructions: "Use for Go code changes and modifications"
        - label: "dependencies"
          instructions: "Use for dependency updates and package changes"
        - label: "documentation"
          instructions: "Use for documentation improvements and updates"
        - label: "testing"
          instructions: "Use for test-related changes and test infrastructure"
        - label: "performance"
          instructions: "Use for performance optimizations and improvements"
        - label: "ci"
          instructions: "Use for CI/CD and GitHub Actions changes"
        - label: "breaking_change"
          instructions: "Use for incompatible changes and major updates"
        - label: "security"
          instructions: "Use for security-related fixes and improvements"
        - label: "windows"
          instructions: "Use for Windows platform-specific changes"
    path_filters: []
    path_instructions:
        - path: "*.go"
          instructions: |
              Core tail library: Focus on correctness, race safety, and API stability.
              - Verify goroutine lifecycle management (tomb/context) is correct
              - Check for race conditions in concurrent file access
              - Ensure proper resource cleanup (file handles, watchers)
              - Validate error handling covers real failure modes
              - Confirm backward API compatibility is maintained
              - Keep the public API surface minimal
        - path: "watch/**/*.go"
          instructions: |
              File watcher implementations: Critical for cross-platform correctness.
              - Verify FileWatcher interface contract is satisfied
              - Check inotify and polling watcher implementations for correctness
              - Ensure proper event handling and error propagation
              - Validate cross-platform behavior (Linux, macOS, Windows, FreeBSD)
              - Check for resource leaks (file descriptors, watchers)
        - path: "ratelimiter/**/*.go"
          instructions: |
              Rate limiter: Ensure correctness of leaky bucket implementation.
              - Verify rate limiting logic is mathematically correct
              - Check for race conditions in concurrent usage
              - Ensure proper time handling
        - path: "util/**/*.go"
          instructions: |
              Utilities: Keep simple and focused.
              - Verify utility functions are correct and well-tested
              - Check for unnecessary complexity
        - path: "winfile/**/*.go"
          instructions: |
              Windows file handling: Platform-specific correctness.
              - Verify Windows file open flags are correct
              - Check for proper error handling of Windows-specific errors
              - Ensure compatibility with different Windows versions
        - path: "cmd/**/*.go"
          instructions: |
              CLI tool (gotail): Focus on user experience and correctness.
              - Verify flag handling and error messages
              - Ensure proper signal handling for clean shutdown
        - path: "**/*_test.go"
          instructions: |
              Test files: Follow test proportionality principles.
              - Verify tests cover critical functionality and real edge cases
              - Check table-driven tests are well-organized and clear
              - Ensure test names clearly describe what is being tested
              - Validate mocks/fixtures are necessary and not over-engineered
              - Confirm tests are shorter and simpler than implementation
              - Check error cases are tested but not every possible variation
        - path: "docs/**/*.md"
          instructions: |
              Documentation: Ensure clarity, accuracy, and completeness.
              - Verify examples are correct and runnable
              - Check documentation matches current library behavior
              - Validate links and references are current
    abort_on_close: true
    disable_cache: false
    auto_review:
        enabled: true
        auto_incremental_review: true
        ignore_title_keywords: ["WIP"]
        labels: []
        drafts: false
        base_branches: ["master"]
    finishing_touches:
        docstrings:
            enabled: true
        unit_tests:
            enabled: true
    pre_merge_checks:
        docstrings:
            mode: warning
            threshold: 80
        title:
            mode: warning
            requirements: Must follow conventional commit format
        description:
            mode: warning
        issue_assessment:
            mode: warning
    tools:
        ast-grep:
            rule_dirs: []
            util_dirs: []
            essential_rules: true
            packages: []
        shellcheck:
            enabled: true
        ruff:
            enabled: false
        markdownlint:
            enabled: true
        github-checks:
            enabled: true
            timeout_ms: 300000
        languagetool:
            enabled: true
            enabled_rules: []
            disabled_rules: []
            enabled_categories: []
            disabled_categories: []
            enabled_only: false
            level: default
        biome:
            enabled: false
        hadolint:
            enabled: false
        swiftlint:
            enabled: false
        phpstan:
            enabled: false
            level: default
        phpmd:
            enabled: false
        phpcs:
            enabled: false
        golangci-lint:
            enabled: true
        yamllint:
            enabled: true
        gitleaks:
            enabled: true
        checkov:
            enabled: true
        detekt:
            enabled: false
        eslint:
            enabled: false
        flake8:
            enabled: false
        rubocop:
            enabled: false
        buf:
            enabled: false
        regal:
            enabled: false
        actionlint:
            enabled: true
        pmd:
            enabled: false
        cppcheck:
            enabled: false
        semgrep:
            enabled: true
        circleci:
            enabled: true
        clippy:
            enabled: false
        sqlfluff:
            enabled: false
        prismaLint:
            enabled: false
        pylint:
            enabled: false
        oxc:
            enabled: false
        shopifyThemeCheck:
            enabled: false
        luacheck:
            enabled: false
        brakeman:
            enabled: false
        dotenvLint:
            enabled: true
        htmlhint:
            enabled: false
        checkmake:
            enabled: true
chat:
    auto_reply: true
    integrations:
        jira:
            usage: disabled
        linear:
            usage: disabled
knowledge_base:
    opt_out: false
    web_search:
        enabled: true
    code_guidelines:
        enabled: true
        filePatterns:
            - "**/*.go"
            - "**/*.md"
            - "**/justfile"
            - "**/*.yaml"
            - "**/*.yml"
    learnings:
        scope: auto
    issues:
        scope: auto
    jira:
        usage: disabled
        project_keys: []
    linear:
        usage: disabled
        team_keys: []
    pull_requests:
        scope: auto
code_generation:
    docstrings:
        language: en-US
        path_instructions:
            - path: "*.go"
              instructions: |
                  Library code documentation should explain purpose and usage.
                  - Focus on package-level documentation explaining domain
                  - Document exported functions/types with purpose and usage
                  - Include examples for complex APIs
                  - Explain non-obvious behavior or edge cases
                  - Keep implementation details in code comments, not godoc
                  - Follow Go doc comment conventions
            - path: "watch/**/*.go"
              instructions: |
                  Watcher documentation should explain platform behavior.
                  - Document FileWatcher interface contract clearly
                  - Explain platform-specific behavior differences
                  - Note resource management requirements
            - path: "**/*_test.go"
              instructions: |
                  Test documentation should explain what is being validated.
                  - Use descriptive test function names instead of excessive comments
                  - Document table-driven test structure when complex
                  - Explain test fixtures or mock setup when non-obvious
                  - Avoid redundant documentation for self-explanatory tests
    unit_tests:
        path_instructions:
            - path: "*.go"
              instructions: |
                  Library tests: Focus on correctness and edge cases.
                  - Test concurrent access and race conditions
                  - Verify file rotation handling
                  - Test error conditions (file not found, permission denied)
                  - Use table-driven tests for multiple scenarios
                  - Keep tests simpler than implementation
                  - Avoid testing standard library behavior
            - path: "watch/**/*.go"
              instructions: |
                  Watcher tests: Verify cross-platform behavior.
                  - Test file change detection accuracy
                  - Verify event ordering and delivery
                  - Test error handling for missing files
                  - Use temporary files for test isolation
            - path: "ratelimiter/**/*.go"
              instructions: |
                  Rate limiter tests: Verify timing and correctness.
                  - Test rate limiting under various loads
                  - Verify bucket behavior at boundaries
                  - Test concurrent access safety
            - path: "cmd/**/*.go"
              instructions: |
                  CLI tests: Focus on flag parsing and error handling.
                  - Test flag combinations and validation
                  - Verify error messages for invalid inputs
                  - Keep tests simpler than implementation
issue_enrichment:
    auto_enrich:
        enabled: true
    planning:
        enabled: false
        auto_planning:
            enabled: false
            labels: []
    labeling:
        labeling_instructions:
            - label: "type:feature"
              instructions: "Use for new functionality, feature requests, and enhancements"
            - label: "type:bug"
              instructions: "Use for bug fixes, defect corrections, and issues where something isn't working as expected"
            - label: "enhancement"
              instructions: "Use for improvements to existing features or incremental enhancements"
            - label: "priority:critical"
              instructions: "Use for critical issues requiring immediate attention, security vulnerabilities, or blocking production issues"
            - label: "priority:high"
              instructions: "Use for high priority issues that significantly impact functionality"
            - label: "priority:normal"
              instructions: "Use for standard work items, regular features, and routine bug fixes"
            - label: "bug"
              instructions: "Use when something isn't working correctly — race conditions, crashes, incorrect output"
            - label: "documentation"
              instructions: "Use for improvements to documentation, README updates, code comments, or usage examples"
            - label: "duplicate"
              instructions: "Use when this issue or pull request already exists"
            - label: "invalid"
              instructions: "Use when the issue doesn't seem right or is not applicable"
            - label: "question"
              instructions: "Use when further information or clarification is needed"
            - label: "wontfix"
              instructions: "Use when this issue will not be worked on"
            - label: "good first issue"
              instructions: "Use for well-defined, relatively simple issues good for newcomers"
            - label: "help wanted"
              instructions: "Use when community contributions are especially welcome"
            - label: "go"
              instructions: "Use for Go code changes or Go-specific issues"
            - label: "dependencies"
              instructions: "Use for dependency updates, go.mod changes, or third-party library modifications"
            - label: "ci"
              instructions: "Use for CI/CD pipeline changes, GitHub Actions workflows, or build process modifications"
            - label: "github_actions"
              instructions: "Use specifically for GitHub Actions workflow files or runner-related issues"
            - label: "architecture"
              instructions: "Use for architectural changes, design decisions, or structural improvements"
            - label: "refactoring"
              instructions: "Use for code refactoring or restructuring without changing functionality"
            - label: "cleanup"
              instructions: "Use for code cleanup tasks, removing dead code, or tidying technical debt"
            - label: "technical-debt"
              instructions: "Use for technical debt that needs to be addressed"
            - label: "performance"
              instructions: "Use for performance optimizations or efficiency enhancements"
            - label: "testing"
              instructions: "Use for test infrastructure, test coverage improvements, or test-related changes"
            - label: "breaking_change"
              instructions: "Use for changes that disrupt backward compatibility or change public APIs"
            - label: "security"
              instructions: "Use for security-related features, vulnerability fixes, or security improvements"
            - label: "windows"
              instructions: "Use for Windows platform-specific issues or compatibility"
        auto_apply_labels: true
